Fix Number type checks
codebytere/node-system-displays pull request #2
Opened 2021-10-07 12:09 UTC by onikienko

Current code throws an exception if use `0` for `.screenshot()` bounds or for `.mirror()` secondID

2021-10-07 18:45 UTC, codebytere requested changes
Thanks for this! Just one request, and then i'd also like to add test(s) (e.g. to ensure that 0 works and doesn't throw anymore) to ensure correct behavior before we get this merged 😁

2021-10-07 18:45 UTC, codebytere commented on index.js
> -    } else if (!options.bounds.x || typeof options.bounds.x !== 'number') {
let's replace this check as well as the others with `Object.hasOwnProperty` or `x in options.bounds` instead of deleting it

2021-10-07 19:08 UTC, onikienko commented on index.js
> -    } else if (!options.bounds.x || typeof options.bounds.x !== 'number') {
If honest, I do not see the reason in that check. `options.bounds` is defined and has type `object`.  You ensure this in lines 41 and 42. 
So if `x` in `options.bounds` is not defined, `options.bounds.x` will be `undefined`.  So you will have check like `typeof undefined !== number`.  It's `true` and we will throw an error in next line as expected.
I can't imagine a scenario where we may need this additional check you are asking to add.

2021-10-08 08:33 UTC, onikienko commented
Added tests. One of them to check `options.bounds` against `undefined`. To demonstrate that we do not need more checks here. 
Let me know what do you think.

2021-10-11 19:02 UTC, codebytere approved these changes
fair point - on further thought this is sufficient.

2021-10-11 19:05 UTC, merged

2022-06-27 14:30 UTC, onikienko commented
Hi @codebytere 

Do you plan to publish a new release with this fix?